title: Akeem McNeil # your name (or website title) here
logo: "/images/Akeem McNeil Headshot3.JPEG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  B.I. & Data Analytics Storyteller 
  <br><br>
  Music | Photography | History Channel aficianato
  <br><br>
  <a href="https://www.linkedin.com/in/akeem-mcneil/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
